BITGET_API_KEY = "your_bitget_api_key_here"
# TWITTER_BEARER = "your_twitter_bearer_token_here"  # Removed due to API authentication issues
# REDDIT_CLIENT_ID = "your_reddit_client_id_here"  # Removed due to API authentication issues
# REDDIT_CLIENT_SECRET = "your_reddit_client_secret_here"  # Removed due to API authentication issues  
# REDDIT_USER_AGENT = "your_reddit_user_agent_here"  # Removed due to API authentication issues
DUNE_API_KEY = "your_dune_api_key_here"
SANTIMENT_API_KEY = "your_santiment_api_key_here"
CMCAL_API_KEY = "your_coinmarketcal_api_key_here"
CRYPTOPANIC_API_KEY = "your_cryptopanic_api_key_here"
LUNARCRUSH_API_KEY = "your_lunarcrush_api_key_here"
MESSARI_API_KEY = "your_messari_api_key_here"
THEGRAPH_ENDPOINT = "your_thegraph_endpoint_here"